### ISSUE TITLE
DX12 crash

### ISSUE THREAD

**Issue by RaedAbbas** [millicast/millicast-publisher-unreal-engine-plugin#1]
The engine crashes if DX12 is used. It works fine on DX11. This means lost of visual quality. Moving forward this is also needed for UE5 and its Nanite and Lumen. Any DX12 support tips please?

**Comment by dbaldassi** [comment]
I have added code to read texture when using DX12.
It is in the UE5 branch.

**Comment by RaedAbbas** [comment]
this awesome.. will give that another test soon-ish.. thank you very much :)
