### ISSUE TITLE
Editor freezes when a publisher is publishing in PIE and the PIE session stops

### ISSUE THREAD

**Issue by QuentinGarou** [millicast/millicast-publisher-unreal-engine-plugin#11]
I'm using the main branch for this plugin on a UE5.0.3 from the launcher.
When Publishing content the UMillicastPublisherComponent, stopping the PIE session makes the editor freeze.
Here should be the repro steps:
- Create a new project
- Add this plugin
- Follow the documentation to create a blueprint to publish content with the MillicastViewportCapturer and the MillicastPublisher components.
- Make sure the RenderTarget in the MillicastPublisherSource is the one coming from the MillicastViewportCapturer
- On Begin Play of this blueprint Call Publish from your MillicastPublisher. 
- Press play in the selected viewport
- Wait a little bit to be sure your are really publishing 
- Stop the PIE session and see your editor freezing 

Note: Even having the Unpublish node being called on EndPlay doesn't help.

Here is a snippet of the logs that should help debugging:

> [2022.08.18-16.48.29:136][486]LogMillicastPublisher: Director response : 
>  { 
> 
> [2022.08.18-16.48.29:136][486]LogMillicastPublisher: WsUrl : w 
> jwt : e
> [2022.08.18-16.48.29:136][486]LogMillicastPublisher: Start WebSocket connection
> [2022.08.18-16.48.30:279][494]LogMillicastPublisher: Millicast WebSocket Connected
> [2022.08.18-16.48.30:279][494]LogMillicastPublisher: Creating FWebRTCPeerConnectionFactory
> [2022.08.18-16.48.30:290][494]LogMillicastPublisher: Display: RegisterAudioCallback
> [2022.08.18-16.48.30:290][494]LogMillicastPublisher: Start capture
> [2022.08.18-16.48.30:290][494]LogMillicastPublisher: Created video track
> [2022.08.18-16.48.30:290][494]LogMillicastPublisher: Add transceiver for 楶敤o track : 敲摮牥琭牡敧⵴牴捡k浯
> [2022.08.18-16.48.30:386][494]LogMillicastPublisher: Starting audio capture
> [2022.08.18-16.48.30:388][494]LogMillicastPublisher: Add transceiver for 畡楤o track : 畡楤o
> [2022.08.18-16.48.30:388][494]LogMillicastPublisher: Create offer
> [2022.08.18-16.48.30:390][494]LogMillicastPublisher: Display: pc.createOffer() | sucess
> sdp : v=0
> o=- 9092150707401999253 2 IN IP4 127.0.0.1
> s=-
> t=0 0
> a=group:BUNDLE 0 1
> a=msid-semantic: WMS unrealstream
> m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 102 103 104
> c=IN IP4 0.0.0.0
> a=rtcp:9 IN IP4 0.0.0.0
> a=ice-ufrag:DfkJ
> a=ice-pwd:Ab3y+W8688X7tvg3VKmXcuuF
> a=ice-options:trickle renomination
> a=fingerprint:sha-256 04:71:7C:38:3D:29:80:F1:74:37:0F:CB:39:B8:A6:C6:57:83:1B:2F:83:0A:5F:03:69:FD:37:E6:06:97:68:7D
> a=setup:actpass
> a=mid:0
> a=extmap:14 urn:ietf:params:rtp-hdrext:toffset
> a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
> a=extmap:13 urn:3gpp:video-orientation
> a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
> a=extmap:12 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
> a=extmap:11 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
> a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
> a=extmap:8 http://tools.ietf.org/html/draft-ietf-avtext-framemarking-07
> a=extmap:9 http://www.webrtc.org/experiments/rtp-hdrext/color-space
> a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
> a=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
> a=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
> a=sendonly
> a=msid:unrealstream render-target-track
> a=rtcp-mux
> a=rtcp-rsize
> a=rtpmap:96 VP8/90000
> a=rtcp-fb:96 goog-remb
> a=rtcp-fb:96 transport-cc
> a=rtcp-fb:96 ccm fir
> a=rtcp-fb:96 nack
> a=rtcp-fb:96 nack pli
> a=rtpmap:97 rtx/90000
> a=fmtp:97 apt=96
> a=rtpmap:98 VP9/90000
> a=rtcp-fb:98 goog-remb
> a=rtcp-fb:98 transport-cc
> a=rtcp-fb:98 ccm fir
> a=rtcp-fb:98 nack
> a=rtcp-fb:98 nack pli
> a=fmtp:98 profile-id=0
> a=rtpmap:99 rtx/90000
> a=fmtp:99 apt=98
> a=rtpmap:100 VP9/90000
> a=rtcp-fb:100 goog-remb
> a=rtcp-fb:100 transport-cc
> a=rtcp-fb:100 ccm fir
> a=rtcp-fb:100 nack
> a=rtcp-fb:100 nack pli
> a=fmtp:100 profile-id=2
> a=rtpmap:101 rtx/90000
> a=fmtp:101 apt=100
> a=rtpmap:102 red/90000
> a=rtpmap:103 rtx/90000
> a=fmtp:103 apt=102
> a=rtpmap:104 ulpfec/90000
> a=ssrc-group:FID 1480363673 3104198439
> a=ssrc:1480363673 cname:ClmJ6CQxnylegKvj
> a=ssrc:1480363673 msid:unrealstream render-target-track
> a=ssrc:1480363673 mslabel:unrealstream
> a=ssrc:1480363673 label:render-target-track
> a=ssrc:3104198439 cname:ClmJ6CQxnylegKvj
> a=ssrc:3104198439 msid:unrealstream render-target-track
> a=ssrc:3104198439 mslabel:unrealstream
> a=ssrc:3104198439 label:render-target-track
> m=audio 9 UDP/TLS/RTP/SAVPF 111 110
> c=IN IP4 0.0.0.0
> a=rtcp:9 IN IP4 0.0.0.0
> a=ice-ufrag:DfkJ
> a=ice-pwd:Ab3y+W8688X7tvg3VKmXcuuF
> a=ice-options:trickle renomination
> a=fingerprint:sha-256 04:71:7C:38:3D:29:80:F1:74:37:0F:CB:39:B8:A6:C6:57:83:1B:2F:83:0A:5F:03:69:FD:37:E6:06:97:68:7D
> a=setup:actpass
> a=mid:1
> a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
> a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
> a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
> a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
> a=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
> a=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
> a=sendonly
> a=msid:unrealstream audio
> a=rtcp-mux
> a=rtpmap:111 opus/48000/2
> a=rtcp-fb:111 transport-cc
> a=fmtp:111 minptime=10;useinbandfec=1
> a=rtpmap:110 telephone-event/48000
> a=ssrc:3133723911 cname:ClmJ6CQxnylegKvj
> a=ssrc:3133723911 msid:unrealstream audio
> a=ssrc:3133723911 mslabel:unrealstream
> a=ssrc:3133723911 label:audio
> 
> [2022.08.18-16.48.30:390][494]LogMillicastPublisher: Warning: AudioDeviceModule has not been iniatilized
> [2022.08.18-16.48.30:400][494]LogMillicastPublisher: pc.setLocalDescription() | sucess
> [2022.08.18-16.48.30:400][494]LogMillicastPublisher: WebSocket publish payload : {
> [2022.08.18-16.48.30:400][494]LogSlate: Took 0.000867 seconds to synchronously load lazily loaded font '../../../Engine/Content/Slate/Fonts/DroidSansFallback.ttf' (3848K)
> [2022.08.18-16.48.30:400][494]LogSlate: Last resort fallback font was requested. Font: '../../../Engine/Content/Slate/Fonts/DroidSansFallback.ttf', Character: '⵴ (U+2d74)'
> [2022.08.18-16.48.30:402][494]LogSlate: Took 0.001567 seconds to synchronously load lazily loaded font '../../../Engine/Content/SlateDebug/Fonts/LastResort.ttf' (5269K)
> [2022.08.18-16.48.30:610][504]LogMillicastPublisher: Millicast WebSocket new Message : {"type":"response","transId":41,"data":{"uuid":"feeds://b055d5542d524d0ba56b7e6aaac3717a/257c73a6-eb8b-4f3d-8ca2-b69ac178e81e","feedId":"257c73a6-eb8b-4f3d-8ca2-b69ac178e81e","publisherId":"b055d5542d524d0ba56b7e6aaac3717a","clusterId":"do-sfo-legacy","streamId":"VdHyHW/TestPublish","sdp":"v=0\r\no=- 1660841311148 1 IN IP4 127.0.0.1\r\ns=semantic-sdp\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\na=ice-lite\r\na=msid-semantic: WMS *\r\na=group:BUNDLE 0 1\r\nm=video 9 UDP/TLS/RTP/SAVPF 96 97\r\na=rtpmap:96 VP8/90000\r\na=rtpmap:97 rtx/90000\r\na=fmtp:97 apt=96\r\na=rtcp-fb:96 ccm fir\r\na=rtcp-fb:96 nack \r\na=rtcp-fb:96 nack pli\r\na=rtcp-fb:96 transport-cc \r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id\r\na=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id\r\na=setup:passive\r\na=mid:0\r\na=recvonly\r\na=ice-ufrag:80f7cdc09eba4875\r\na=ice-pwd:018ef09fbb62103e81f9134b8f1a402b9a7c15dd1ead858b\r\na=fingerprint:sha-256 5D:98:61:58:CF:19:DA:A7:6D:43:5C:F8:3D:CA:1E:3E:31:46:97:35:2E:2C:F2:05:9F:85:E8:E3:E4:ED:3F:CD\r\na=candidate:1 1 UDP 2130706431 138.68.239.147 54436 typ host\r\na=rtcp-mux\r\na=rtcp-rsize\r\nm=audio 9 UDP/TLS/RTP/SAVPF 111\r\na=rtpmap:111 opus/48000/2\r\na=fmtp:111 minptime=10;stereo=1;useinbandfec=1\r\na=rtcp-fb:111 transport-cc \r\na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=setup:passive\r\na=mid:1\r\na=recvonly\r\na=ice-ufrag:80f7cdc09eba4875\r\na=ice-pwd:018ef09fbb62103e81f9134b8f1a402b9a7c15dd1ead858b\r\na=fingerprint:sha-256 5D:98:61:58:CF:19:DA:A7:6D:43:5C:F8:3D:CA:1E:3E:31:46:97:35:2E:2C:F2:05:9F:85:E8:E3:E4:ED:3F:CD\r\na=candidate:1 1 UDP 2130706431 138.68.239.147 54436 typ host\r\na=rtcp-mux\r\na=rtcp-rsize\r\n"}}
> [2022.08.18-16.48.30:616][504]LogMillicastPublisher: Set remote description suceeded
> [2022.08.18-16.48.30:616][504]LogBlueprintUserMessages: [Actor_Blueprint_C_0] Warning: Publishing...
> [2022.08.18-16.48.31:125][533]LogMillicastPublisher: Init recording
> [2022.08.18-16.48.31:125][533]LogMillicastPublisher: Start Recording
> [2022.08.18-16.48.34:855][735]LogSlate: Updating window title bar state: overlay mode, drag disabled, window buttons hidden, title bar hidden
> [2022.08.18-16.48.34:855][735]LogWorld: BeginTearingDown for /Game/Maps/UEDPIE_0_QuentinTEst
> [2022.08.18-16.48.34:855][735]LogMillicastPublisher: Display: Unpublish
> [2022.08.18-16.48.34:873][735]LogMillicastPublisher: Display: Stop capture
>

**Comment by dbaldassi** [comment]
I am mostly testing in PlayInEditor, but I have never encountered such issue.
Which operating system are you using ?
