### ISSUE TITLE
No SceneCapture2D

### ISSUE THREAD

**Issue by SonarSystems** [millicast/millicast-publisher-unreal-engine-plugin#12]
I cannot find a SceneCapture2D, I created a new blueprint class and in there added a SceneCaptureComponent2D. But I can't find a way to create a Render Target. I think because I am using UE 5.0.3 some aspects of the engine are different. New steps are required to set it up in UE >= 5.0.3

Help would be greatly appreciated.

**Comment by dbaldassi** [comment]
By the way, you should prefer to use the millicast camera actor instead of a SceneCapture2d

**Comment by SonarSystems** [comment]
I don't have the option to add a capture2D or millicast camera actor. What
can I do to fix this? Am I missing a step?

**Comment by dbaldassi** [comment]
They are in the actor panel list of unreal engine.
![image](https://user-images.githubusercontent.com/49135375/192759683-4e45b7e9-d8c2-4988-88f0-b322495d3fdc.png)

**Comment by dbaldassi** [comment]
in the millicast dashboards, in your stream settings, you have the url to the hoster player :
![image](https://user-images.githubusercontent.com/49135375/192760561-e835ea17-64b4-4cd2-b192-bdcb9450fa75.png)

There is also the link to embed it in an iframe

**Comment by dbaldassi** [comment]
Or you can use the javascript SDK

**Comment by SonarSystems** [comment]
I can't seem to find that part of the website for the hosted player path
and link to embed it in an iframe or the JavaScript SDK. Could you help me
out? This is what I see.

**Comment by dbaldassi** [comment]
https://docs.dolby.io/streaming-apis/docs/how-to-broadcast-in-dashboard

**Comment by SonarSystems** [comment]
How do I set up the Live broadcast steaming token to be able to stream my
unreal project to the web, what specifically do I need to set in the images
I sent

**Comment by SonarSystems** [comment]
![1](https://user-images.githubusercontent.com/6967779/192985592-8c470f89-1b37-4939-951c-abc6f3838642.PNG)
![2](https://user-images.githubusercontent.com/6967779/192985580-1174aebd-bb16-4c5f-968e-216d3ad2cb0f.PNG)
![3](https://user-images.githubusercontent.com/6967779/192985588-5708165c-9088-4f16-89c6-22dec5bc8f00.PNG)

**Comment by dbaldassi** [comment]
I think I don't understand your question sorry.
You just have to put the stream name of the dashboard in the stream name section of the pub source.
Same for publishing token.
Then you just have to start the publishing in the blueprint.
And to see the stream in a browser, you just need to open the hosted player.
I mean, everything is explained in the docs.

**Comment by SonarSystems** [comment]
I put the stream name into the pub source name stream name section. Also did it for publishing token.

I have also started the publishing in the blueprint. 

But nothing appears as can be seen even when I broadcast. It's just blank. I run my project in UE and still nothing.

![1](https://user-images.githubusercontent.com/6967779/192993649-79f50e96-2a2b-454c-a4da-d9306815c627.PNG)
![2](https://user-images.githubusercontent.com/6967779/192993650-6f46b64e-117a-441e-b3d9-e232dce85f47.PNG)
![3](https://user-images.githubusercontent.com/6967779/192993897-9ab1c499-b7f0-4b53-add3-9d39047236c7.PNG)

**Comment by dbaldassi** [comment]
Did you set the millicast publisher source in the Publisher component ?
![image](https://user-images.githubusercontent.com/49135375/192998930-d01b41b1-ee64-494b-add9-52b681b94dae.png)

**Comment by dbaldassi** [comment]
Also there is a demo project for publishing, you can strat from here.
https://github.com/millicast/millicast-publisher-ue5-example

**Comment by SonarSystems** [comment]
Yes the publisher source is set. I am downloading the demo project now

**Comment by SonarSystems** [comment]
Getting this error when opening the demo

![1](https://user-images.githubusercontent.com/6967779/193013117-3dba0f8c-80fd-4a1d-acf1-84b25ff683b6.PNG)

**Comment by SonarSystems** [comment]
What am I missing in my project, how do I get the stream from UE to appear in my hosted player?

**Comment by dbaldassi** [comment]
Maybe log when you get event from the publisher, to check that your authentication is successful and you are actually publishing, and you're not getting any error.

**Comment by dbaldassi** [comment]
Oh and did you put your blueprint in your world ?

**Comment by SonarSystems** [comment]
Blueprint wasn't added, added now. Still not working, not sure what I am missing.

**Comment by dbaldassi** [comment]
Can you log these events to check : 
- OnPublishing
- OnPublishingError
- OnAuthentication
- OnAuthentication Failure

**Comment by SonarSystems** [comment]
How do I add these events, I can't find them in all actions.

![Untitled](https://user-images.githubusercontent.com/6967779/193576589-16ab3715-8816-4b18-92b7-8316695e0f41.png)

**Comment by SonarSystems** [comment]
Better screenshot than before

![Untitled](https://user-images.githubusercontent.com/6967779/193576998-a241d105-1abf-4152-913e-0fa9b414db5d.png)

**Comment by dbaldassi** [comment]
They are not there. Click on the your MillicastPUblisher component, they are appearing in the right panel, at the bottom.

**Comment by SonarSystems** [comment]
![Capture](https://user-images.githubusercontent.com/6967779/193582441-0bfca5d5-f976-4d35-836f-62cfd31bf902.PNG)

**Comment by dbaldassi** [comment]
So it means you are publishing. Now can you open the viewer : https://viewer.millicast.com/?streamId=ACCOUNT_ID/STREAM_NAME
And open the stats ?

**Comment by dbaldassi** [comment]
Looking at previous screenshot, it seems that your stream name is : ``l8ms2fvo``
But you have entered ``SeeTest `` in the publisher source

**Comment by SonarSystems** [comment]
It's working now.

Do have another issue, when trying to run the RTMP stream in VLC and using FFPlay it does not work. Any ideas?

**Comment by dbaldassi** [comment]
No I don't have any idea about VLC FFPlay sorry. 
it is not related to the unreal engine plugin so I'm closing the issue.

**Comment by craig-johnston** [comment]
@SonarSystems if you'd like help with the other parts of our service, please contact our support https://support.dolby.io/
