### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by RaedAbbas** [millicast/millicast-publisher-unreal-engine-plugin#2]
![image](https://user-images.githubusercontent.com/87811633/173864128-dba8b79e-c686-4f92-bfb8-167d37c88dd3.png)
I get this error at the first run but it continues fine to the editor if I ignore it and press Continue

**Comment by dbaldassi** [comment]
I have fix it by unregistering the millicast style before.
The fix is in the UE5 branch.
