### ISSUE TITLE
Building crashes ERROR: "already defined in Module.PixelStreaming.cpp.obj"

### ISSUE THREAD

**Issue by shtronly** [millicast/millicast-publisher-unreal-engine-plugin#20]
Hi,
In editor the v 1.2.0 runs flawless and I am also able to built my game using 1.1.0. However, whenever I try to built my game or any other blank project with 1.2.0 I get the following Error. I also reinstalled Pixelstreaming plugin, but whenever both are running it does not built. Any idea how I can fix this? I would be totally fine without the logging the WebRTC. I just need the plugin to work like in the editor. 

UATHelper: Packaging (Windows): Module.MillicastPublisher.cpp.obj : error LNK2005: "void __cdecl RedirectWebRtcLogsToUnreal(enum rtc::LoggingSeverity)" (?RedirectWebRtcLogsToUnreal@@YAXW4LoggingSeverity@rtc@@@z) already defined in Module.PixelStreaming.cpp.obj
UATHelper: Packaging (Windows): Creating library H:\UE_Projects\3D_Stream_Demo\Stream_Demo_5\Binaries\Win64\Stream_Demo_5-Win64-Shipping.lib and object H:\UE_Projects\3D_Stream_Demo\Stream_Demo_5\Binaries\Win64\Stream_Demo_5-Win64-Shipping.exp
UATHelper: Packaging (Windows): H:\UE_Projects\3D_Stream_Demo\Stream_Demo_5\Binaries\Win64\Stream_Demo_5-Win64-Shipping.exe : fatal error LNK1169: one or more multiply defined symbols found
UATHelper: Packaging (Windows): Took 1127.0406541s to run UnrealBuildTool.exe, ExitCode=6

**Comment by shtronly** [comment]
Was able to fix it by removing: 
#include "WebRTC/WebRTCLog.h"

and further down

RedirectWebRtcLogsToUnreal(rtc::LoggingSeverity::LS_VERBOSE);

inside the file: MillicastPublisherModule.cpp

and also deleting files:
WebRTCLog.h and WebRTCLog.cpp in /pivate/WebRTC

**Comment by dbaldassi** [comment]
PixelStreaming and the millicast plugin must have the same signature. 
I think we can fix this by putting a namespace around this function
