### ISSUE TITLE
Unable to use plugin on 5.1.0

### ISSUE THREAD

**Issue by Briggs599** [millicast/millicast-publisher-unreal-engine-plugin#21]
Once I've installed the plugin, the engine prompts me to build the files from source since they are from a different version of Unreal. When I do this the compile fails.

Generating VS Studio project files also fails with the plugins included.

**Comment by dbaldassi** [comment]
The plugin is not yet available for 5.1.0. 
I will note this in the readme.

**Comment by dbaldassi** [comment]
Unreal 5.1 support now available here : https://github.com/millicast/millicast-publisher-unreal-engine-plugin/tree/UE5.1
