### ISSUE TITLE
4 to 5 second delay when streaming audio

### ISSUE THREAD

**Issue by MaximeM** [millicast/millicast-publisher-unreal-engine-plugin#24]
Hey there,

Video works really great but when streaming audio and listening in  the browser it will be delayed by at least 4 second.

Anyway to have a more instantaneous audio?

**Comment by dbaldassi** [comment]
I never noticed this. 
Can you tell me the steps to reproduce this ?

**Comment by MaximeM** [comment]
It seems to appear in PIE only. 
Standalone solves the latency part
