### ISSUE TITLE
Can it be used on localhost

### ISSUE THREAD

**Issue by sqlpxc** [millicast/millicast-publisher-unreal-engine-plugin#25]
I tried to use it in the localhost environment, so I wrote a simple WebSocket server and modified MillicastPublisherComponent.cpp but it didn't work, I confirmed that the sdp information was exchanged, did I miss any steps?

Here is my code：
[req.zip](https://github.com/millicast/millicast-publisher-unreal-engine-plugin/files/10343876/req.zip)

![屏幕截图 2023-01-04 173857](https://user-images.githubusercontent.com/38583139/210551615-eae6994a-39c6-4a0a-9125-00ecd778c102.png)

**Comment by dbaldassi** [comment]
The plugin is designed to authenticate and publish to a Millicast server. Do you run a Millicast server in local ?

**Comment by sqlpxc** [comment]
Do you mean this: https://github.com/millicast/millicast-spaces-server
I'm not running locally, I want to learn how this plugin works, so I changed the source code to try.

**Comment by dbaldassi** [comment]
No it is not a Millicast server. The millicast server is hosted in the cloud, you need to have an account to use it.
You can read the docs to see how to get started https://docs.dolby.io/streaming-apis/docs

**Comment by sqlpxc** [comment]
So is there a way to run it locally?

**Comment by dbaldassi** [comment]
Not really, we don't provide the code or a binary of the server.

**Comment by sqlpxc** [comment]
well thank you anyway
