### ISSUE TITLE
RP - Dynamic bandwidth not going under 4mbps

### ISSUE THREAD

**Issue by Neosettler** [millicast/millicast-publisher-unreal-engine-plugin#27]
Set Maximum bitrate in Unreal blueprint doesn't go below 4mbps for some reason.

**Comment by Neosettler** [comment]
Quality settings logic:
![image](https://user-images.githubusercontent.com/4521415/213797227-afd21592-5cca-4f43-997a-d65e24282ae6.png)
![image](https://user-images.githubusercontent.com/4521415/213797326-205a6e44-837a-4856-b52f-b72629ff5927.png)

**Comment by rweber89** [comment]
@Neosettler just checking here from the screenshot it seems like you are printing the value of the local Bitrate variable, which would not change when calling any of the MillicastPublisher functions. Could you please elaborate a bit on the details?
