### ISSUE TITLE
RP - MillicastViewportCapturer render target missing objects

### ISSUE THREAD

**Issue by Neosettler** [millicast/millicast-publisher-unreal-engine-plugin#28]
The MillicastViewportCapturer seems to have an issue with terrain and/or material that makes the mesh hidden from the final capture2d.

**Comment by Neosettler** [comment]
![image](https://user-images.githubusercontent.com/4521415/213795989-10efe41f-87dd-42bf-9e62-5c7e8334f9c2.png)

**Comment by Neosettler** [comment]
![image](https://user-images.githubusercontent.com/4521415/213796407-e315577b-a239-4454-a037-bc72fad2d352.png)

**Comment by Neosettler** [comment]
if you look closely, the standard capture2d on screens (BLUE) works as expected, the Millicast capture (RED) does not
![image](https://user-images.githubusercontent.com/4521415/213796637-0cb0ef4a-d047-4491-84f6-31429c7113e6.png)

**Comment by dbaldassi** [comment]
I manage to reproduce it by just by using a landscape component in my project.
So I'm pretty sure there is something going with the landscape. The texture must be unload when you go far away. I tried to modify the level of details of the landscape and the camera (disable the post process effets, subsection min component screensize, static lighting LOD). nothing yet.

The preview of the cinecamera is working, the editor viewport is working, only the render target output have the missing texture. Tried several options in the ViewFamily, ViewFamiliyOptions and EngineShowFlags, nothing yet. Still working on it.

**Comment by dbaldassi** [comment]
I have replaced the millicast viewport inheriting from a cinecamera to a scencapture2d instead.
This solve the landscape disapearing. I had a darker color issue at first, but replacing the render target format in the render texture settings by RTF RGBA8 SRGB solved this darker color issue.
https://github.com/millicast/millicast-publisher-unreal-engine-plugin/tree/quality-issue
