### ISSUE TITLE
RP - h264 simulcast on publisher plugin

### ISSUE THREAD

**Issue by jchang0419** [millicast/millicast-publisher-unreal-engine-plugin#33]
This is a feature request to add h264 simulcast to the publisher plugin.

vp8 is not ideal due to the lack of hw encoding.

**Comment by dbaldassi** [comment]
Update on simulcast:
We manage to have simulcast working for both VP8 and H264. The work is in the h264-simulcast branch.
We still are facing an issue : we get darker color on the 2 inferiors layers. Once that is fixed, the simulcast feature will be ready to merge.

**Comment by dbaldassi** [comment]
We now have simulcast working for both VP8 and H264. This feature in in the dev branch.

**Comment by dbaldassi** [comment]
This has been merged to main.
