### ISSUE TITLE
RP - Couldn't get capture buffer

### ISSUE THREAD

**Issue by Neosettler** [millicast/millicast-publisher-unreal-engine-plugin#34]
Having an issue where the MillicastViewportCapturer stops rendering:

LogMillicastPublisher: Error: Couldn't get capture buffer.... 

Cause is unknown. Very random and difficult to reproduce but on a long enough timeline, it will eventually happen.

**Comment by rweber89** [comment]
@Neosettler just to clarify, does this happen on a continuously running instance of the game? Or are there restarts inbetween inbetween, like multiple usage of PIE inside the editor? Clarifying the exact circumstances of when you get this to appear might be helpful.

The log message will also contain the reason why it is happening, if you could provide us with the entire message that would be great 🙏

**Comment by Neosettler** [comment]
> just to clarify, does this happen on a continuously running instance of the game? 

Yes, in a shipping build running but I've been abled to reproduce this in editor running on a long enough timeline.
[SV_Sunset-backup-2023.01.30-04.51.24 (2).log](https://github.com/millicast/millicast-publisher-unreal-engine-plugin/files/10677909/SV_Sunset-backup-2023.01.30-04.51.24.2.log)

**Comment by rweber89** [comment]
@Neosettler thank you! I have put up a PR to fix our logging a bit. I will be in touch - I cannot promise how quickly I will get to this, as I am still getting acquainted with the project.

Once this happens, it stops rendering and never starts again?

**Comment by Neosettler** [comment]
the mechanic is that we have over 100s cameras and we switch from one to another by enabling which MillicastViewportCapturer writes to a unique render target 2d like so:

![image](https://user-images.githubusercontent.com/4521415/217394895-6ef89933-08c3-455a-8b87-63541e1b4147.png)

after a while, the switch has no effect and it sticks to the last camera that was last activated, any other calls to activate or deactivate has no affects.

**Comment by rweber89** [comment]
@Neosettler quick clarification, does it still update the render target from that camera? Like if a player moves in front of it?

Because it could simply no longer be drawing to the render target, rather than still being on the last active camera, which is what I would probably expect to be happening. So you'd always see whatever was last drawn to it.

**Comment by Neosettler** [comment]
Still rendering, yes!
